  name: fancy2
  run-name: fancy running2
  on:
    - push
  jobs:
    something2:
      runs-on: ubuntu-latest
      steps:
        - run: echo "cloning java"
        - uses: actions/checkout@v4
        - name: installing java
          uses: actions/setup-java@v4
          with:
            java-version: 21
            distribution: adopt
        - run: echo "compiling java"
        - run: ls -r ${{github.workspace}}
        - name: clean install
          run: (mvn package -U) && (mvn install -U) && (mvn dependency:resolve -U)
        - name: maven tests
          run: mvn test
