  name: fancy2
  run-name: fancy running2
  on:
    - push
  jobs:
    something2:
      runs-on: ubuntu-latest
      steps:
        - run: echo "compiling java"
        - run: ls ${{github.workspace}}
        - run: javac main.java
        - run: java main
